---
# Task definition

platform: linux
container_limits: {}

# Use the 'python:3.8-slim-buster' image from Docker Hub
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.8-slim-buster

# We will provide an input called 'src' to this Task
inputs:
  - name: git
outputs:
  - name: build

# What do we want this task to do?
# Tell Concourse the commands it should execute, in this Task
run:
  path: /bin/sh
  args:
  - -c
  - |
    ls -l; ls-l git/;cd git/src; python3 app_test.py; 
